name: build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    
    - name: Install libGTK-3, pkg-config and OpenSSH headers
      run: sudo apt-get install libgtk-3-dev pkg-config libssl-dev
      
    - name: Setup Node & Yarn
      run: yarn install
    
    - name: Install Tauri CLI
      run: yarn add -D @tauri-apps/cli

    - name: Template command
      run: echo "Hello, world!"

    - name: Initiating manual OpenSSL build
      run: git clone git://git.openssl.org/openssl.git && cd openssl

    - name: Configuring OpenSSL
      run: ./config --openssldir=/usr/local/ssl

    - name: Making OpenSSL...
      run: make

    - name: Testing OpenSSL...
      run: make test

    - name: Installing OpenSSL...
      run: sudo make install

    - name: Setting environment variables
      run: export OPENSSL_DIR="/usr/local/ssl"
    
    - name: Build GMPublisher
      run: yarn tauri build

    - name: Bundle up
      run: cargo run --manifest-path src-tauri/Cargo.toml -- bundle
