name: build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    
    - name: Install GUI and OpenSSH headers
      run: sudo apt-get install libgtk-3-dev libssl-dev
      
    - name: Setup Node & Yarn
      run: yarn install
    
    - name: Install Tauri Bundler
      run: yarn add -D @tauri-apps/cli

    #- name: Setup environment variables
    #  run: export OPENSSL_DIR=$(openssl version -d | cut -c 14- | rev | cut -c 2- | rev)

    - name: Setup environment variables
      run: export OPENSSL_NO_VENDOR=1
    
    - name: Build
      run: yarn tauri build

    - name: Bundle up
      run: cargo run --manifest-path src-tauri/Cargo.toml -- bundle
