name: build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2

    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3
    
    - name: Install dependencies
      run: sudo apt install libgtk-3-dev libgtksourceview-3.0-dev libwebkit2gtk-4.0-dev libsoup2.4-dev
      
    - name: Setup Node & Yarn
      run: yarn install
    
    - name: Install Tauri CLI
      run: yarn add -D @tauri-apps/cli

    - name: Template command
      run: echo "Hello, world!"

    #- name: Building and installing OpenSSL
    #  run: | 
    #    git clone git://git.openssl.org/openssl.git
    #    cd openssl
    #    ./config --openssldir=/usr/local/ssl
    #    make
    #    make test
    #    sudo make install

    - name: Setting environment variables
      run: |
        export OPENSSL_DIR="/usr/local/ssl"
        export OPENSSL_LIB_DIR="/usr/lib/x86_64-linux-gnu" 
        export OPENSSL_INCLUDE_DIR="/usr/include/openssl" 
    
    - name: Build GMPublisher
      run: yarn tauri build

    - name: Bundle up
      run: cargo run --manifest-path src-tauri/Cargo.toml -- bundle
