name: build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2

    - name: Install dependencies
      run: sudo apt install libgtk-3-dev libgtksourceview-3.0-dev libwebkit2gtk-4.0-dev libsoup2.4-dev
      
    - name: Setup Node & Yarn
      run: yarn install
    
    #- name: Install Tauri CLI
    #  run: yarn add -D @tauri-apps/cli

    - name: Download and extract steamworks v1.51 (151)
      run: |
        wget https://partner.steamgames.com/downloads/steamworks_sdk_151.zip
        mkdir ./steamworks
        unzip steamworks_sdk_151.zip -d ./steamworks

    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3
    
    - name: Build GMPublisher
      run: |
        cd src-tauri
        STEAM_SDK_LOCATION=$(echo $(pwd)/../steamworks) cargo build --release
        cd ..

    - name: Setup README-Install.txt
      run: |
        echo Put gmpublisher file from artifact into /usr/bin >> README-Install.txt
        echo Put libsteam_api.so file from artifact to /usr/lib >> README-Install.txt
        echo If you want, put gmpublisher.desktop file to ~/.local/share/applications/gmpublisher.desktop >> README-Install.txt

    - name: Make gmpublisher.desktop file
      run: |
        echo "[Desktop Entry]"  >> gmpublisher.desktop
        echo "Type=Application" >> gmpublisher.desktop
        echo "Name=gmpublisher" >> gmpublisher.desktop
        echo "Exec=/usr/bin/gmpublisher" >> gmpublisher.desktop
        echo "TryExec=gmpublisher" >> gmpublisher.desktop
        echo "Comment=A powerful and feature-packed Workshop publisher for Garry's Mod!" >> gmpublisher.desktop

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: gmpublisher
        path: |
          src-tauri/target/release/gmpublisher
          src-tauri/target/release/libsteam_api.so
          gmpublisher.desktop
          README-Install.txt
