name: build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    
    - name: Install GUI
      run: sudo apt-get install libgtk-3-dev
      
    - name: Setup Node & Yarn
      run: yarn install
    
    - name: Install Tauri Bundler
      run: cargo install tauri-ctl --force
    
    - name: Build
      run: yarn run tauri build --release
  
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      
    - name: Setup Node & Yarn
      run: yarn install
    
    - name: Install Tauri Bundler
      run: cargo install tauri-bundler --force
        
    - name: Build
      run: yarn run tauri build --release
  
  build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      
    - name: Setup Node & Yarn
      run: yarn install
    
    - name: Install Tauri Bundler
      run: cargo install tauri-bundler --force
        
    - name: Build
      run: yarn run tauri build --release
